/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package magazyn;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;

/**
 *
 * @author kabot
 */
public class ProductDialog extends javax.swing.JDialog
{
  Product prod;
  private Magazyn mag;

  /**
    * Creates new form ProductDialog
    */
  public ProductDialog(java.awt.Frame parent, int prodId)
  {
    super(parent, true);

    initComponents();

    prodIlosc.requestFocus();

    setValues(prodId);

    getRootPane();
  }

  private void setValues(int prodId)
  {
    HashMap<Integer, KeyValue> magList;

    mag = new Magazyn();
    magList = mag.getList();

    for (Map.Entry<Integer, KeyValue> m : magList.entrySet()) {
      magCombo.addItem(m.getValue());
    }

    prod = new Product(prodId);

    prodName.setText(prod.name);
    prodJm.setText(prod.um);
    prodVat.setText(Integer.toString(prod.vat));
    prodCena.setText(Float.toString(prod.price));
    obecnaIlosc.setText(Float.toString(prod.quantity));

    magCombo.setSelectedItem(magList.get(prod.magId));

    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    prodData.setText(dateFormat.format(new Date()));

  }

  @Override
  protected JRootPane createRootPane()
  {
    //http://www.javaworld.com/javaworld/javatips/jw-javatip72.html

    ActionListener actionEnter = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent evt) {
        saveProduct();
      }
    };

    ActionListener actionEsc = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent evt) {
        dispose();
      }
    };

    JRootPane rootP = new JRootPane();
    rootP.registerKeyboardAction(actionEnter,
                                 KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
                                 JComponent.WHEN_IN_FOCUSED_WINDOW);
    rootP.registerKeyboardAction(actionEsc,
                                 KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                                 JComponent.WHEN_IN_FOCUSED_WINDOW);

    return rootP;
  }

  private void saveProduct()
  {
    boolean ok = true;

    // http://www.devdaily.com/java/java-uimanager-color-keys-list
    final Color bg = UIManager.getColor("TextField.background");

    prodName.setToolTipText(null);
    prodName.setBackground(bg);
    prodData.setToolTipText(null);
    prodData.setBackground(bg);
    prodIlosc.setToolTipText(null);
    prodIlosc.setBackground(bg);
    prodCena.setToolTipText(null);
    prodCena.setBackground(bg);
    prodVat.setToolTipText(null);
    prodVat.setBackground(bg);

    if (prodName.getText().isEmpty()) {
      prodName.setToolTipText("Nie podano nazwa produktu");
      prodName.setBackground(Color.red);
      ok = false;
    }

    if (!prodData.getText().matches("^[0-9]{4}-[0-9]{2}-[0-9]{2}$")) {
      prodData.setToolTipText("Poprawny format daty: 9999-99-99");
      prodData.setBackground(Color.red);
      ok = false;
    }
    

    if (!prodIlosc.getText().isEmpty()) {
      try {
        prod.quantity += Float.valueOf(prodIlosc.getText());
      }
      catch (NumberFormatException e) {
        prodIlosc.setToolTipText("Poprawny format ilości: 9.99");
        prodIlosc.setBackground(Color.red);
        ok = false;
      }
    }

    try {
      prod.price = Float.valueOf(prodCena.getText());
    }
    catch (NumberFormatException e) {
      prodCena.setToolTipText("Poprawny format ceny: 9.99");
      prodCena.setBackground(Color.red);
      ok = false;
    }

    try {
      prod.vat = Integer.valueOf(prodVat.getText());
    }
    catch (NumberFormatException e) {
      prodVat.setToolTipText("Poprawny format stawki vat: 99");
      prodVat.setBackground(Color.red);
      ok = false;
    }

    if (!ok) {
      return;
    }
    
    prod.um = prodJm.getText();
    prod.name = prodName.getText();
    prod.magId = ((KeyValue)magCombo.getSelectedItem()).key;
    prod.date = prodData.getText();

    prod.save();

    dispose();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        magCombo = new javax.swing.JComboBox();
        prodName = new javax.swing.JTextField();
        prodJm = new javax.swing.JTextField();
        prodVat = new javax.swing.JTextField();
        prodIlosc = new javax.swing.JTextField();
        prodCena = new javax.swing.JTextField();
        prodData = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        obecnaIlosc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Magazyn");

        jLabel2.setText("Nazwa");

        jLabel3.setText("Jm");

        jLabel4.setText("Vat");

        jLabel5.setText("Ilość");

        jLabel6.setText("Cena");

        jLabel7.setText("Data");

        prodName.setToolTipText("");

        prodData.setText("2012-01-30");

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("Zapisz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapisz(evt);
            }
        });

        jButton2.setText("Zapisz jako nowy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszNowy(evt);
            }
        });

        jButton3.setText("Anuluj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnuluj(evt);
            }
        });

        jButton4.setText("Usuń");

        jLabel8.setText("+");

        obecnaIlosc.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(magCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prodData, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(prodCena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                            .addComponent(prodIlosc, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prodVat, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prodJm, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(obecnaIlosc)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(magCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodJm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodVat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodIlosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(obecnaIlosc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(prodCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZapisz(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapisz
        saveProduct();
    }//GEN-LAST:event_btnZapisz

    private void btnZapiszNowy(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszNowy
        System.out.println("zapisznowy");
    }//GEN-LAST:event_btnZapiszNowy

    private void btnAnuluj(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnuluj
        dispose();
    }//GEN-LAST:event_btnAnuluj

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox magCombo;
    private javax.swing.JLabel obecnaIlosc;
    private javax.swing.JTextField prodCena;
    private javax.swing.JTextField prodData;
    private javax.swing.JTextField prodIlosc;
    private javax.swing.JTextField prodJm;
    private javax.swing.JTextField prodName;
    private javax.swing.JTextField prodVat;
    // End of variables declaration//GEN-END:variables
}
