/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lwh;

import kbt.Config;

/**
 *
 * @author kabot
 */
public class UpgradeDialog extends javax.swing.JDialog
{

  private Upgrade upg;

  /**
   * Creates new form UpgradeDialog
   */
  public UpgradeDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();

    int upgVer, curVer;

    upg = new Upgrade();
    upg.setUrl(Config.get("magazyn.upgrade.version"), Config.get("magazyn.upgrade.current"));

    upgVer = upg.getVersion();
    curVer = Integer.parseInt(Config.get("version"));

    currentVersion.setText(Config.get("version"));
    upgradeVersion.setText(Integer.toString(upgVer));

    if (upgVer > curVer) {
      upgNeededInfo.setText("Aktulizacja jest dostępna.");
    }
    else {
      upgradeButton.setEnabled(false);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    currentVersion = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    upgradeVersion = new javax.swing.JLabel();
    upgNeededInfo = new javax.swing.JLabel();
    upgradeButton = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Aktualizacja");

    jLabel1.setText("Aktualnie zainstalowana wersja:");

    currentVersion.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    currentVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    currentVersion.setText("0");

    jLabel3.setText("Wersja dostępna do pobrania:");

    upgradeVersion.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    upgradeVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    upgradeVersion.setText("0");

    upgNeededInfo.setText("Aktualizacja nie jest wymagana.");

    upgradeButton.setText("Pobierz");
    upgradeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        upgradeButtonActionPerformed(evt);
      }
    });

    jButton1.setText("Zamknij");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(upgradeButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1)
                  .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(upgradeVersion)
                  .addComponent(currentVersion)))
              .addComponent(upgNeededInfo))
            .addGap(0, 11, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(currentVersion))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(upgradeVersion))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(upgNeededInfo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1)
          .addComponent(upgradeButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void upgradeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_upgradeButtonActionPerformed
  {//GEN-HEADEREND:event_upgradeButtonActionPerformed
    if (upg.download()) {
      System.out.println("Plik pobrany");
    }
    else {
      System.out.println("Blad aktualizacji");
    }
  }//GEN-LAST:event_upgradeButtonActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
  {//GEN-HEADEREND:event_jButton1ActionPerformed
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel currentVersion;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel upgNeededInfo;
  private javax.swing.JButton upgradeButton;
  private javax.swing.JLabel upgradeVersion;
  // End of variables declaration//GEN-END:variables
}
